apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb-ppe
  name: influxdb-ppe
spec:
  type: NodePort
  ports:
    - name: api
      port: 9999
      targetPort: 9999
      nodePort: 31234
  selector:
    app: influxdb-ppe
