# templates/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ppe-influx
  name: {{ .Values.names.deployment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ppe-influx
  serviceName: {{ .Values.names.service }}
  template:
    metadata:
      labels:
        app: ppe-influx
    spec:
      containers:
        - name: influxdb-ppe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9999
              name: api
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
