# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ppe-influx
  name: {{ .Values.names.service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: ppe-influx
