version: "3"
services:
  redis:
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"
  userapi:
    container_name: nodejs-webapp
    build: ./userapi
    ports:
      - "5000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
