apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodejsApp.name.serviceName }}
  labels:
    app: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
