apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nodejsApp.name.deploymentName }}
spec:
  replicas: {{ .Values.nodejsApp.replicas | default "1" }}
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: {{ .Values.nodejsApp.image.repository }}:{{ .Values.nodejsApp.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: {{ .Values.nodejsApp.env.REDIS_HOST }}
            - name: REDIS_PORT
              value: "{{ .Values.nodejsApp.env.REDIS_PORT }}"
