apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name.serviceName  }}
  labels:
    app: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.nodejsApp.env.REDIS_PORT }}
      targetPort: {{ .Values.nodejsApp.env.REDIS_PORT }}
