apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.name.pvName }}
  labels:
    type: local
    app: redis-pv
spec:
  capacity:
    storage: {{ .Values.redis.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
