apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.name.pvcName }}
  labels:
    app: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
