apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  selector:
    app: kubernetes-bootcamp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
