version: '3'
services:
  redis:
    container_name: redis-db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./db:/data/db
  web:
    container_name: nodejs-webapp
    build: .
    ports:
      - "5000:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
