name: Node.js CI

# for each push or PR on branch MAIN
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    #defining env variable for directory architecture
    env:
      working-directory: ./lab_3
      #defining the default running directory
    defaults:
      run:
        working-directory: ./lab_3

    strategy:
      matrix:
        node-version: [18.18.0] #specifying used node version

    steps:
      #REDIS install
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "6.x"
      #REDIS test
      - run: redis-cli ping
        working-directory: ${{env.working-directory}}
      #NODE install
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: ./lab_3
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      #install project dependencies
      - run: npm install
        working-directory: ${{env.working-directory}}
      #run test script to check if the build in working
      - run: npm test
        working-directory: ${{env.working-directory}}
