name: Node.js CI

# for each push or PR on branch MAIN
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    #defining env variable for directory architecture
    env:
      working-directory: ./userapi
      #defining the default running directory
      AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
      NODE_VERSION: '18.18.0'                # set this to the node version to use

    defaults:
      run:
        working-directory: ./userapi

    strategy:
      matrix:
        node-version: [18.18.0] #specifying used node version

    steps:
      #REDIS install
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "6.x"
      #REDIS test
      - name: Redis test
        run: redis-cli ping
        working-directory: ${{env.working-directory}}
      #NODE install
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: ${{env.working-directory}}
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      #install project dependencies
      - name: Installing Node dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      #run test script to check if the build in working
      - name: Running tests
        run: npm test
        working-directory: ${{env.working-directory}}
      #zipping the artificat to then deploy it
      - name: Zip Artifact for deployement
        run: |
          zip -r node-app.zip .
        working-directory: ${{env.working-directory}}
      #publishing the artifact
      - name: Upload artifact for deployement
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip

  deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
  
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
