# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./lab_3
    defaults:
      run:
        working-directory: ./lab_3
      
    strategy:
      matrix:
        node-version: [18.18.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - uses: actions/checkout@v4
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "6.x"
    - run: redis-cli ping
      working-directory: ${{env.working-directory}}

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: ./lab_3
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run:  npm install
      working-directory: ${{env.working-directory}}

    - run:  npm run build --if-present
      working-directory: ${{env.working-directory}}

    - run: npm test
      working-directory: ${{env.working-directory}}

    
